### ISSUE TITLE
apostrophes not escape when downloading osm file

### ISSUE THREAD

**Issue by wvanderp** [Zverik/Level0#33]
Apostrophes are not escaped when downloading a osm file. so, when I try to open this file in josm it complains about an invalid xml file. an example file is included

https://gist.github.com/wvanderp/d4efadb577639d058e60d68b1041fa0e

**Comment by Zverik** [comment]
Fixed in #34.

**Comment by wvanderp** [comment]
there is still an error when uses contain a '. 

like the data here: map=17/51.942767/4.449109


i think is can be fixed by adding a htmlspecialchars($obj[$k], ENT_QUOTES) [here](https://github.com/Zverik/Level0/blob/3f3719fe6f596b473d921e2c17a3161ce046251e/www/osmapi.php#L426)

**Comment by Zverik** [comment]
Thanks, I did that.
